-- Juki Organizer advanced productivity schema
create table if not exists public.recurrence_rules (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null, frequency text not null default 'weeks', interval_value integer not null default 1, weekdays integer[] default '{}', day_of_month integer, time_of_day time, anchor_mode text not null default 'schedule', start_date date, end_date date, active boolean not null default true, created_at timestamptz not null default now());
alter table public.tasks add column if not exists description text, add column if not exists start_date date, add column if not exists start_time time, add column if not exists estimated_minutes integer, add column if not exists recurrence_rule_id uuid references public.recurrence_rules(id) on delete set null, add column if not exists archived_at timestamptz, add column if not exists parent_task_id uuid references public.tasks(id) on delete cascade, add column if not exists sort_order integer default 0;
create table if not exists public.subtasks (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, title text not null, completed boolean not null default false, due_date date, sort_order integer default 0, created_at timestamptz not null default now(), completed_at timestamptz);
create table if not exists public.task_reminders (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, remind_at timestamptz not null, sent_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.task_notes (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, content text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.task_attachments (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, name text not null, url text not null, created_at timestamptz not null default now());
create table if not exists public.task_dependencies (task_id uuid not null references public.tasks(id) on delete cascade, depends_on_task_id uuid not null references public.tasks(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, primary key(task_id,depends_on_task_id));
create table if not exists public.task_history (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, task_id uuid not null references public.tasks(id) on delete cascade, action text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.task_templates (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, description text, color text, tasks jsonb not null default '[]'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.saved_views (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, name text not null, filters jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.goals (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, title text not null, description text, target_date date, status text not null default 'active', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.goal_projects (goal_id uuid not null references public.goals(id) on delete cascade, project_id uuid not null references public.projects(id) on delete cascade, owner_id uuid not null references auth.users(id) on delete cascade, primary key(goal_id,project_id));
DO $$ DECLARE t text; BEGIN FOR t IN SELECT unnest(array['recurrence_rules','subtasks','task_reminders','task_notes','task_attachments','task_dependencies','task_history','task_templates','saved_views','goals','goal_projects']) LOOP EXECUTE format('alter table public.%I enable row level security',t); EXECUTE format('drop policy if exists owner_all on public.%I',t); EXECUTE format('create policy owner_all on public.%I for all using (auth.uid()=owner_id) with check (auth.uid()=owner_id)',t); END LOOP; END $$;
create index if not exists idx_tasks_due on public.tasks(owner_id,due_date); create index if not exists idx_tasks_recurrence on public.tasks(recurrence_rule_id); create index if not exists idx_subtasks_task on public.subtasks(task_id);