import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { CalendarDays, Check, ChevronLeft, ChevronRight, CirclePlus, Clock3, Folder, Inbox, LayoutDashboard, Loader2, LogOut, Plus, Search, Settings2, X, Repeat2, Target, ListChecks, Flame, Droplets, BookOpen, Dumbbell, Utensils, Home, Briefcase, GraduationCap, Heart, ShoppingCart, StickyNote, Timer, MoreHorizontal } from 'lucide-react'
import { supabase } from './supabase'
import './styles.css'

type Project={id:string;name:string;color:string;description?:string|null}
type Task={id:string;title:string;description?:string|null;project_id:string|null;project?:Project|null;priority:string;status:string;completed_at:string|null;due_date:string|null;due_time:string|null;estimated_minutes?:number|null;recurrence_rule_id?:string|null;archived_at?:string|null}
type Rule={id:string;title:string;frequency:string;interval_value:number;weekdays:number[];day_of_month:number|null;time_of_day:string|null;anchor_mode:string;active:boolean;start_date:string|null;end_date:string|null}
type Habit={id:string;name:string;description?:string|null;icon:string;tracking_type:'boolean'|'quantity'|'duration'|'count';target:number;unit:string;frequency:string;weekdays:number[];time:string|null;color:string;active:boolean}
type HabitLog={id:string;habit_id:string;log_date:string;value:number;completed:boolean}
type View='Dashboard'|'Tarefas'|'Hábitos'|'Calendário'|'Projetos'|'Capturar'
const pad=(n:number)=>String(n).padStart(2,'0')
const isoDate=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`
const today=()=>isoDate(new Date())
const addDays=(d:Date,n:number)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}
const startWeek=(d:Date)=>{const x=new Date(d);const day=x.getDay();x.setDate(x.getDate()-(day===0?6:day-1));return x}
const priorityDb=(v:string)=>v==='Alta'?'high':v==='Baixa'?'low':'medium'
const priorityUi=(v:string)=>v==='high'?'Alta':v==='low'?'Baixa':'Média'
const dateLong=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'})
const timeText=(t?:string|null)=>t?t.slice(0,5):''
const icons:any={water:Droplets,read:BookOpen,exercise:Dumbbell,meal:Utensils,home:Home,work:Briefcase,study:GraduationCap,personal:Heart,shopping:ShoppingCart,other:Flame}

function App(){
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[view,setView]=useState<View>('Dashboard'),[tasks,setTasks]=useState<Task[]>([]),[projects,setProjects]=useState<Project[]>([]),[rules,setRules]=useState<Rule[]>([]),[habits,setHabits]=useState<Habit[]>([]),[logs,setLogs]=useState<HabitLog[]>([]),[search,setSearch]=useState(''),[calendarDate,setCalendarDate]=useState(new Date()),[modal,setModal]=useState<'task'|'habit'|'project'|null>(null),[editing,setEditing]=useState<Task|null>(null),[editingHabit,setEditingHabit]=useState<Habit|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authMode,setAuthMode]=useState<'login'|'signup'>('login')
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}).catch(()=>setLoading(false));const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(session)load()},[session])
 async function load(){if(!supabase||!session)return;setError('');try{const [p,t,r,h,l]=await Promise.all([supabase.from('projects').select('*').order('created_at',{ascending:true}),supabase.from('tasks').select('*, project:projects(*)').order('due_date',{ascending:true,nullsFirst:false}).order('due_time',{ascending:true,nullsFirst:false}),supabase.from('recurrence_rules').select('*').order('created_at',{ascending:false}),supabase.from('habits').select('*').eq('active',true).order('created_at',{ascending:true}),supabase.from('habit_logs').select('*').order('log_date',{ascending:false})]);if(p.error||t.error){setError(p.error?.message||t.error?.message||'Não foi possível carregar os dados.');return}setProjects(p.data||[]);setTasks(t.data||[]);if(!r.error)setRules(r.data||[]);if(!h.error)setHabits(h.data||[]);if(!l.error)setLogs(l.data||[])}catch(e){setError('Não foi possível carregar os dados. Verifique o Supabase.')}}
 async function auth(email:string,password:string){if(!supabase)return;setBusy(true);const r=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setBusy(false);if(r.error)setError(r.error.message)}
 async function toggleTask(t:Task){if(!supabase||!session)return;const done=t.status!=='done';const r=await supabase.from('tasks').update(done?{status:'done',completed_at:new Date().toISOString()}:{status:'todo',completed_at:null}).eq('id',t.id).eq('owner_id',session.user.id);if(r.error)setError(r.error.message);else{if(done&&t.recurrence_rule_id)await generateNext(t);await load()}}
 async function generateNext(t:Task){const r=rules.find(x=>x.id===t.recurrence_rule_id);if(!r||!supabase||!session||r.anchor_mode==='completion')return;let base=t.due_date?new Date(`${t.due_date}T12:00:00`):new Date();let next=new Date(base);if(r.frequency==='days')next=addDays(base,Math.max(1,r.interval_value));else if(r.frequency==='weeks')next=addDays(base,7*Math.max(1,r.interval_value));else if(r.frequency==='months'){next=new Date(base);next.setMonth(next.getMonth()+Math.max(1,r.interval_value))}else if(r.frequency==='years'){next=new Date(base);next.setFullYear(next.getFullYear()+Math.max(1,r.interval_value))}if(r.end_date&&isoDate(next)>r.end_date)return;await supabase.from('tasks').insert({owner_id:session.user.id,title:t.title,description:t.description||null,project_id:t.project_id,status:'todo',priority:priorityDb(t.priority),due_date:isoDate(next),due_time:t.due_time||r.time_of_day||null,recurrence_rule_id:r.id,estimated_minutes:t.estimated_minutes||null})}
 async function saveTask(f:any){if(!supabase||!session)return;setBusy(true);const title=f.title?.trim()||'sem título';const due=f.due||'';const payload:any={owner_id:session.user.id,title,description:f.description||null,project_id:f.project||null,status:f.status||'todo',priority:priorityDb(f.priority||'Média'),due_date:due?due.slice(0,10):null,due_time:due?due.slice(11,19):null,estimated_minutes:f.estimated?Number(f.estimated):null};let r=editing?await supabase.from('tasks').update(payload).eq('id',editing.id).eq('owner_id',session.user.id):await supabase.from('tasks').insert(payload).select('id').single();if(r.error){setError(r.error.message);setBusy(false);return}const id=editing?.id||r.data?.id;if(f.recurring&&id){const rr=await supabase.from('recurrence_rules').insert({owner_id:session.user.id,title,frequency:f.frequency,interval_value:Number(f.interval)||1,weekdays:f.weekdays||[],day_of_month:f.dayOfMonth?Number(f.dayOfMonth):null,time_of_day:f.time||due.slice(11,19)||null,anchor_mode:f.anchorMode||'schedule',start_date:f.startDate||due.slice(0,10)||null,end_date:f.endDate||null}).select().single();if(rr.error)setError(rr.error.message);else await supabase.from('tasks').update({recurrence_rule_id:rr.data.id,due_time:due?due.slice(11,19):rr.data.time_of_day||null}).eq('id',id).eq('owner_id',session.user.id)}setBusy(false);setModal(null);setEditing(null);await load()}
 async function saveHabit(f:any){if(!supabase||!session)return;setBusy(true);const payload={owner_id:session.user.id,name:f.name?.trim()||'hábito sem título',description:f.description||null,icon:f.icon||'other',tracking_type:f.trackingType||'boolean',target:Number(f.target)||1,unit:f.unit||'vez',frequency:f.frequency||'daily',weekdays:f.weekdays||[],time:f.time||null,color:f.color||'pink',active:true};const r=editingHabit?await supabase.from('habits').update(payload).eq('id',editingHabit.id).eq('owner_id',session.user.id):await supabase.from('habits').insert(payload);if(r.error)setError(r.error.message);else{setModal(null);setEditingHabit(null);await load()}setBusy(false)}
 async function logHabit(h:Habit,value:number,completed?:boolean){if(!supabase||!session)return;const date=today();const existing=logs.find(x=>x.habit_id===h.id&&x.log_date===date);const nextValue=h.tracking_type==='boolean'?(completed?1:0):Math.max(0,(existing?.value||0)+value);const done=h.tracking_type==='boolean'?!!completed:nextValue>=h.target;const r=await supabase.from('habit_logs').upsert({...(existing?{id:existing.id}:{}),owner_id:session.user.id,habit_id:h.id,log_date:date,value:nextValue,completed:done,updated_at:new Date().toISOString()},{onConflict:'habit_id,log_date'});if(r.error)setError(r.error.message);else await load()}
 async function addProject(name:string,color:string){if(!supabase||!session)return;setBusy(true);const r=await supabase.from('projects').insert({owner_id:session.user.id,name:name.trim()||'novo projeto',color});if(r.error)setError(r.error.message);else{setModal(null);await load()}setBusy(false)}
 const visible=useMemo(()=>tasks.filter(t=>!t.archived_at&&(!search||`${t.title} ${t.description||''} ${t.project?.name||''}`.toLowerCase().includes(search.toLowerCase()))),[tasks,search])
 const todayTasks=visible.filter(t=>t.due_date===today()),open=todayTasks.filter(t=>t.status!=='done'),overdue=visible.filter(t=>t.status!=='done'&&t.due_date&&t.due_date<today())
 if(loading)return <div className="loading-screen"><Loader2 className="spin"/> carregando...</div>
 if(!supabase)return <AuthScreen mode={authMode} setMode={setAuthMode} onAuth={auth} busy={busy} error="Supabase não está configurado."/>
 if(!session)return <AuthScreen mode={authMode} setMode={setAuthMode} onAuth={auth} busy={busy} error={error}/>
 return <div className="app-shell"><Sidebar view={view} setView={setView} logout={()=>supabase?.auth.signOut()}/><main className="main"><header className="topbar"><div className="mobile-logo">juki<span>°</span></div><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="buscar na sua vida..."/></div><div className="top-actions"><button className="icon-button" onClick={()=>setModal('habit')} title="novo hábito"><CirclePlus size={19}/></button><div className="avatar">{session.user.email?.[0]?.toUpperCase()}</div></div></header><section className="content">{error&&<div className="error-banner">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}
 {view==='Dashboard'&&<Dashboard date={today()} tasks={open} overdue={overdue} habits={habits} logs={logs} projects={projects} onTask={toggleTask} onHabit={logHabit} onNewTask={()=>{setEditing(null);setModal('task')}} onNewHabit={()=>{setEditingHabit(null);setModal('habit')}}/>}
 {view==='Tarefas'&&<TasksPage tasks={visible} onToggle={toggleTask} onEdit={t=>{setEditing(t);setModal('task')}} onNew={()=>{setEditing(null);setModal('task')}}/>}
 {view==='Hábitos'&&<HabitsPage habits={habits} logs={logs} onLog={logHabit} onNew={()=>{setEditingHabit(null);setModal('habit')}} onEdit={h=>{setEditingHabit(h);setModal('habit')}}/>}
 {view==='Calendário'&&<CalendarPage date={calendarDate} setDate={setCalendarDate} tasks={visible} rules={rules}/>} 
 {view==='Projetos'&&<ProjectsPage projects={projects} tasks={tasks} onNew={()=>setModal('project')}/>} 
 {view==='Capturar'&&<Capture onSave={async text=>{setEditing(null);setModal('task');setDraft(text)}}/>}
 </section></main><nav className="mobile-nav"><button onClick={()=>setView('Dashboard')} className={view==='Dashboard'?'active':''}><LayoutDashboard/><span>início</span></button><button onClick={()=>setView('Tarefas')} className={view==='Tarefas'?'active':''}><Inbox/><span>tarefas</span></button><button onClick={()=>setView('Hábitos')} className={view==='Hábitos'?'active':''}><Flame/><span>hábitos</span></button><button onClick={()=>setView('Calendário')} className={view==='Calendário'?'active':''}><CalendarDays/><span>calendário</span></button><button onClick={()=>{setEditing(null);setModal('task')}}><Plus/><span>novo</span></button></nav>
 {modal==='task'&&<TaskModal task={editing} projects={projects} initialTitle={draft} onClose={()=>{setModal(null);setEditing(null);setDraft('')}} onSave={saveTask} busy={busy}/>} {modal==='habit'&&<HabitModal habit={editingHabit} onClose={()=>{setModal(null);setEditingHabit(null)}} onSave={saveHabit} busy={busy}/>} {modal==='project'&&<ProjectModal onClose={()=>setModal(null)} onSave={addProject} busy={busy}/>}</div>
}
let draft='';const setDraft=(v:string)=>{draft=v}
function AuthScreen({mode,setMode,onAuth,busy,error}:{mode:'login'|'signup';setMode:(m:'login'|'signup')=>void;onAuth:(e:string,p:string)=>void;busy:boolean;error:string}){const [email,setEmail]=useState(''),[pass,setPass]=useState('');return <div className="auth-wrap"><div className="auth-card"><div className="brand-mark">juki<span>°</span></div><p className="eyebrow">organizador da sua vida</p><h1>{mode==='login'?'bem-vinda de volta ♡':'crie seu espaço'}</h1><p>casa, trabalho, faculdade, hábitos e tudo que faz parte do seu dia.</p><label>e-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>senha<input value={pass} onChange={e=>setPass(e.target.value)} type="password"/></label>{error&&<div className="error-box">{error}</div>}<button className="primary full" disabled={busy} onClick={()=>onAuth(email,pass)}>{busy?'aguarde...':mode==='login'?'entrar':'criar conta'}</button><button className="link-button" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'ainda não tenho uma conta':'já tenho uma conta'}</button></div></div>}
function Sidebar({view,setView,logout}:{view:View;setView:(v:View)=>void;logout:()=>void}){const items:[View,any,string][]=[['Dashboard',<LayoutDashboard/>,'início'],['Tarefas',<Inbox/>,'tarefas'],['Hábitos',<Flame/>,'hábitos'],['Calendário',<CalendarDays/>,'calendário'],['Projetos',<Folder/>,'projetos'],['Capturar',<CirclePlus/>,'capturar']];return <aside className="sidebar"><div className="logo">juki<span>°</span></div><div className="sidebar-label">minha vida</div>{items.map(([v,i,l])=><button key={v} className={`side-button ${view===v?'active':''}`} onClick={()=>setView(v)}>{i}<span>{l}</span></button>)}<div className="sidebar-bottom"><button className="side-button" onClick={()=>alert('Configurações em breve ♡')}><Settings2/><span>configurações</span></button><button className="side-button" onClick={logout}><LogOut/><span>sair</span></button></div></aside>}
function Dashboard({date,tasks,overdue,habits,logs,projects,onTask,onHabit,onNewTask,onNewHabit}:{date:string;tasks:Task[];overdue:Task[];habits:Habit[];logs:HabitLog[];projects:Project[];onTask:(t:Task)=>void;onHabit:(h:Habit,v:number,c?:boolean)=>void;onNewTask:()=>void;onNewHabit:()=>void}){const done=habits.filter(h=>logs.find(l=>l.habit_id===h.id&&l.log_date===date)?.completed).length;return <><div className="welcome"><div><p className="eyebrow">seu espaço</p><h1>bom dia, júlia ♡</h1><p>{dateLong(date)}</p></div><div className="hero-actions"><button className="ghost" onClick={onNewHabit}><Flame size={16}/> novo hábito</button><button className="primary" onClick={onNewTask}><Plus size={16}/> nova tarefa</button></div></div><div className="stats-grid"><Stat title="para hoje" value={tasks.length} tone="pink" icon={<Clock3/>}/><Stat title="hábitos" value={`${done}/${habits.length}`} tone="lavender" icon={<Flame/>}/><Stat title="atrasadas" value={overdue.length} tone="yellow" icon={<Repeat2/>}/><Stat title="projetos" value={projects.length} tone="sage" icon={<Folder/>}/></div><div className="home-grid"><section className="panel"><SectionTitle title="hoje" subtitle="suas próximas coisas" action="nova tarefa" onClick={onNewTask}/>{tasks.length?<div className="timeline">{tasks.slice(0,8).map(t=><TaskLine key={t.id} t={t} onToggle={()=>onTask(t)}/>)}</div>:<Empty text="nada marcado para hoje ♡"/>}</section><section className="panel"><SectionTitle title="hábitos de hoje" subtitle={`${done} de ${habits.length} concluídos`} action="ver hábitos" onClick={onNewHabit}/>{habits.slice(0,5).map(h=><HabitMini key={h.id} h={h} log={logs.find(l=>l.habit_id===h.id&&l.log_date===date)} onLog={onHabit}/>)}{!habits.length&&<Empty text="crie seu primeiro hábito"/>}</section><section className="panel wide"><SectionTitle title="próximos dias" subtitle="o que vem por aí"/><div className="upcoming">{[1,2,3].map(n=>{const d=isoDate(addDays(new Date(),n));const ts=(tasks as Task[]).filter(t=>t.due_date===d);return <div className="up-day" key={d}><b>{new Date(`${d}T12:00:00`).toLocaleDateString('pt-BR',{weekday:'short',day:'numeric'})}</b><span>{ts.length?ts[0].title:'dia tranquilo ♡'}</span></div>})}</div></section></div></>}
function Stat({title,value,tone,icon}:{title:string;value:any;tone:string;icon:any}){return <div className={`stat-card ${tone}`}><div className="stat-top"><span>{title}</span>{icon}</div><strong>{value}</strong></div>}
function SectionTitle({title,subtitle,action,onClick}:{title:string;subtitle?:string;action?:string;onClick?:()=>void}){return <div className="section-title"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{action&&<button className="text-button" onClick={onClick}>{action} →</button>}</div>}
function TaskLine({t,onToggle}:{t:Task;onToggle:()=>void}){return <div className="task-line"><button className={`check ${t.status==='done'?'checked':''}`} onClick={onToggle}>{t.status==='done'&&<Check size={14}/>}</button><div className="task-copy"><b>{t.title}</b><small>{t.project?.name||'pessoal'}{t.recurrence_rule_id&&' · recorrente'}</small></div><span className="task-time">{timeText(t.due_time)}</span></div>}
function HabitMini({h,log,onLog}:{h:Habit;log?:HabitLog;onLog:(h:Habit,v:number,c?:boolean)=>void}){const I=icons[h.icon]||Flame;const pct=h.tracking_type==='boolean'?(log?.completed?100:0):Math.min(100,((log?.value||0)/h.target)*100);return <div className="habit-mini"><div className={`habit-icon ${h.color}`}><I size={19}/></div><div className="habit-copy"><b>{h.name}</b><small>{h.tracking_type==='boolean'?'todos os dias':`${log?.value||0} / ${h.target} ${h.unit}`}</small><div className="progress"><i style={{width:`${pct}%`}}/></div></div>{h.tracking_type==='boolean'?<button className={`round-done ${log?.completed?'done':''}`} onClick={()=>onLog(h,0,!log?.completed)}>{log?.completed?<Check size={16}/>:''}</button>:<button className="add-progress" onClick={()=>onLog(h,h.tracking_type==='duration'?5:250)}>+</button>}</div>}
function TasksPage({tasks,onToggle,onEdit,onNew}:{tasks:Task[];onToggle:(t:Task)=>void;onEdit:(t:Task)=>void;onNew:()=>void}){return <><PageHead title="tarefas" subtitle="tudo que precisa acontecer" action="nova tarefa" onClick={onNew}/><div className="panel task-panel">{tasks.length?tasks.map(t=><div className="task-row-large" key={t.id}><button className={`check ${t.status==='done'?'checked':''}`} onClick={()=>onToggle(t)}>{t.status==='done'&&<Check size={14}/>}</button><div className="task-copy"><b>{t.title}</b><small>{t.project?.name||'pessoal'} · {t.due_date||'sem data'} {timeText(t.due_time)}</small></div><span className={`priority ${t.priority}`}>{priorityUi(t.priority)}</span><button className="more" onClick={()=>onEdit(t)}><MoreHorizontal size={18}/></button></div>):<Empty text="você ainda não tem tarefas"/>}</div></>}
function HabitsPage({habits,logs,onLog,onNew,onEdit}:{habits:Habit[];logs:HabitLog[];onLog:(h:Habit,v:number,c?:boolean)=>void;onNew:()=>void;onEdit:(h:Habit)=>void}){const date=today();const done=habits.filter(h=>logs.find(l=>l.habit_id===h.id&&l.log_date===date)?.completed).length;return <><PageHead title="hábitos" subtitle={`${done} de ${habits.length} concluídos hoje`} action="novo hábito" onClick={onNew}/><div className="habit-summary"><div><span>hábitos de hoje</span><strong>{done}/{habits.length}</strong><small>{habits.length?Math.round(done/habits.length*100):0}% concluído</small></div><div className="circle-progress" style={{'--p':`${habits.length?done/habits.length*360:0}deg`} as any}>{done}</div></div><div className="habit-list">{habits.map(h=><HabitCard key={h.id} h={h} log={logs.find(l=>l.habit_id===h.id&&l.log_date===date)} onLog={onLog} onEdit={()=>onEdit(h)}/>)}{!habits.length&&<div className="panel"><Empty text="ainda não há hábitos. comece por algo pequeno ♡"/></div>}</div></>}
function HabitCard({h,log,onLog,onEdit}:{h:Habit;log?:HabitLog;onLog:(h:Habit,v:number,c?:boolean)=>void;onEdit:()=>void}){const I=icons[h.icon]||Flame;const pct=h.tracking_type==='boolean'?(log?.completed?100:0):Math.min(100,((log?.value||0)/h.target)*100);const freq=h.frequency==='weekdays'?'dias úteis':h.frequency==='weekly'?'semanal':'todos os dias';return <div className="habit-card"><div className={`habit-icon big ${h.color}`}><I size={23}/></div><div className="habit-copy"><b>{h.name}</b><small>↻ {freq}{h.time&&` · ${timeText(h.time)}`}</small><div className="progress"><i style={{width:`${pct}%`}}/></div><small>{h.tracking_type==='boolean'?(log?.completed?'concluído ♡':'ainda não feito'):`${log?.value||0} / ${h.target} ${h.unit}`}</small></div><button className="edit-round" onClick={onEdit}><MoreHorizontal size={17}/></button>{h.tracking_type==='boolean'?<button className={`round-done big ${log?.completed?'done':''}`} onClick={()=>onLog(h,0,!log?.completed)}>{log?.completed?<Check size={18}/>:''}</button>:<button className="primary small" onClick={()=>onLog(h,h.tracking_type==='duration'?5:250)}>+ registrar</button>}</div>}
function CalendarPage({date,setDate,tasks,rules}:{date:Date;setDate:(d:Date)=>void;tasks:Task[];rules:Rule[]}){const [mode,setMode]=useState<'week'|'month'|'day'>('week');const [expanded,setExpanded]=useState(true);const virtual=useMemo(()=>{const out:{task:Task;date:string}[]=[];const start=mode==='month'?new Date(date.getFullYear(),date.getMonth(),1):mode==='day'?new Date(date):startWeek(date);const days=mode==='month'?new Date(date.getFullYear(),date.getMonth()+1,0).getDate():mode==='day'?1:7;for(let i=0;i<days;i++){const d=addDays(start,i);const ds=isoDate(d);tasks.filter(t=>t.due_date===ds).forEach(t=>out.push({task:t,date:ds}));rules.forEach(r=>{if(!r.active||!r.start_date||ds<r.start_date||(r.end_date&&ds>r.end_date))return;if(tasks.some(t=>t.recurrence_rule_id===r.id&&t.due_date===ds))return;const startD=new Date(`${r.start_date}T12:00:00`);const diff=Math.floor((d.getTime()-startD.getTime())/86400000);let match=false;if(r.frequency==='days')match=diff>=0&&diff%Math.max(1,r.interval_value)===0;else if(r.frequency==='weeks')match=diff>=0&&diff%(7*Math.max(1,r.interval_value))===0;else if(r.frequency==='months')match=d.getDate()===(r.day_of_month||startD.getDate())&&(d.getFullYear()>startD.getFullYear()||d.getMonth()>=startD.getMonth());else if(r.frequency==='years')match=d.getMonth()===startD.getMonth()&&d.getDate()===startD.getDate();if(r.weekdays?.length)match=match||r.weekdays.includes(d.getDay());if(match){const base=tasks.find(t=>t.recurrence_rule_id===r.id)||tasks.find(t=>t.title===r.title);if(base)out.push({task:{...base,id:`virtual-${r.id}-${ds}`,due_date:ds,due_time:r.time_of_day||base.due_time},date:ds})}})}return out},[date,tasks,rules,mode]);const title=mode==='day'?date.toLocaleDateString('pt-BR',{day:'numeric',month:'long'}):date.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});return <><div className="calendar-toolbar"><div><p className="eyebrow">planejamento</p><h1>{title}</h1></div><div className="view-switch"><button className={mode==='day'?'active':''} onClick={()=>setMode('day')}>dia</button><button className={mode==='week'?'active':''} onClick={()=>setMode('week')}>semana</button><button className={mode==='month'?'active':''} onClick={()=>setMode('month')}>mês</button></div><div className="calendar-nav"><button className="icon-button soft" onClick={()=>setDate(addDays(date,mode==='week'?-7:mode==='day'?-1:-30))}><ChevronLeft/></button><button className="today-btn" onClick={()=>setDate(new Date())}>hoje</button><button className="icon-button soft" onClick={()=>setDate(addDays(date,mode==='week'?7:mode==='day'?1:30))}><ChevronRight/></button></div></div>{mode==='week'||mode==='day'?<Timeline mode={mode} date={date} items={virtual}/>:<MonthGrid date={date} items={virtual}/>}<button className="calendar-note" onClick={()=>setExpanded(!expanded)}><Repeat2 size={15}/> as tarefas recorrentes aparecem automaticamente no calendário {expanded?'':'· toque para ver'}</button></>}
function Timeline({mode,date,items}:{mode:'week'|'day';date:Date;items:{task:Task;date:string}[]}){const days=mode==='day'?[date]:Array.from({length:7},(_,i)=>addDays(startWeek(date),i));return <div className="timeline-calendar"><div className="timeline-days">{days.map(d=><div className={`day-column ${isoDate(d)===today()?'today':''}`} key={isoDate(d)}><div className="day-header"><span>{d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span><b>{d.getDate()}</b></div><div className="day-events">{Array.from({length:16},(_,i)=>i+7).map(hour=><div className="hour-slot" key={hour}><span>{pad(hour)}:00</span>{items.filter(x=>x.date===isoDate(d)&&Number((x.task.due_time||'').slice(0,2))===hour).map(x=><div className="calendar-event" key={x.task.id}><b>{x.task.title}</b><small>{timeText(x.task.due_time)}{x.task.recurrence_rule_id&&' · ↻'}</small></div>)}</div>)}</div></div>)}</div></div>}
function MonthGrid({date,items}:{date:Date;items:{task:Task;date:string}[]}){const first=new Date(date.getFullYear(),date.getMonth(),1);const offset=(first.getDay()+6)%7;const total=new Date(date.getFullYear(),date.getMonth()+1,0).getDate();const cells=Array.from({length:Math.ceil((offset+total)/7)*7},(_,i)=>i-offset+1);return <div className="month-wrap"><div className="weekday-row">{['seg','ter','qua','qui','sex','sáb','dom'].map(x=><span key={x}>{x}</span>)}</div><div className="month-grid">{cells.map(n=>{const d=n>0&&n<=total?new Date(date.getFullYear(),date.getMonth(),n):null;const ds=d&&isoDate(d);const ev=ds?items.filter(x=>x.date===ds):[];return <div className={`month-cell ${ds===today()?'today':''}`} key={n}>{d&&<><b>{n}</b>{ev.map(x=><div className="month-event" key={x.task.id}>{timeText(x.task.due_time)} {x.task.title}</div>)}</>}</div>})}</div></div>}
function ProjectsPage({projects,tasks,onNew}:{projects:Project[];tasks:Task[];onNew:()=>void}){return <><PageHead title="projetos" subtitle="coisas que levam mais de um passo" action="novo projeto" onClick={onNew}/><div className="project-grid">{projects.map(p=><div className="project-card" key={p.id}><div className={`project-dot ${p.color}`}/><div><h3>{p.name}</h3><p>{tasks.filter(t=>t.project_id===p.id&&t.status!=='done').length} pendentes</p></div></div>)}{!projects.length&&<div className="panel"><Empty text="crie um projeto para agrupar tarefas maiores"/></div>}</div></>}
function Capture({onSave}:{onSave:(t:string)=>void}){const [text,setText]=useState('');return <div className="capture-card"><Inbox size={28}/><p className="eyebrow">captura rápida</p><h1>tira isso da cabeça ♡</h1><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="qualquer coisa que você precisa lembrar..."/><div className="capture-actions"><button className="primary" onClick={()=>{if(text.trim())onSave(text.trim())}}>transformar em tarefa</button></div></div>}
function PageHead({title,subtitle,action,onClick}:{title:string;subtitle:string;action:string;onClick:()=>void}){return <div className="page-head"><div><p className="eyebrow">juki organizer</p><h1>{title}</h1><p>{subtitle}</p></div><button className="primary" onClick={onClick}><Plus size={16}/>{action}</button></div>}
function Empty({text}:{text:string}){return <div className="empty"><div className="empty-icon"><Heart size={19}/></div><p>{text}</p></div>}
function TaskModal({task,projects,initialTitle,onClose,onSave,busy}:{task:Task|null;projects:Project[];initialTitle:string;onClose:()=>void;onSave:(f:any)=>void;busy:boolean}){const [f,setF]=useState<any>({title:task?.title||initialTitle,description:task?.description||'',project:task?.project_id||'',priority:priorityUi(task?.priority||'medium'),due:task?.due_date?`${task.due_date}T${task.due_time||'09:00'}`:'',recurring:!!task?.recurrence_rule_id,frequency:'weeks',interval:1,time:task?.due_time||'09:00',anchorMode:'schedule',startDate:task?.due_date||today(),endDate:''});const u=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));return <Modal title={task?'editar tarefa':'nova tarefa'} onClose={onClose}><label>título<input value={f.title} onChange={e=>u('title',e.target.value)} placeholder="ex.: lavar roupa"/></label><label>descrição<textarea value={f.description} onChange={e=>u('description',e.target.value)} placeholder="opcional"/></label><div className="form-grid"><label>data e horário<input type="datetime-local" value={f.due} onChange={e=>u('due',e.target.value)}/></label><label>prioridade<select value={f.priority} onChange={e=>u('priority',e.target.value)}>{['Alta','Média','Baixa'].map(x=><option key={x}>{x}</option>)}</select></label></div><label>projeto<select value={f.project} onChange={e=>u('project',e.target.value)}><option value="">pessoal / sem projeto</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="switch-row"><input type="checkbox" checked={f.recurring} onChange={e=>u('recurring',e.target.checked)}/> repetir esta tarefa</label>{f.recurring&&<div className="recurrence-box"><div className="form-grid"><label>repetir<select value={f.frequency} onChange={e=>u('frequency',e.target.value)}><option value="days">a cada X dias</option><option value="weeks">a cada X semanas</option><option value="months">a cada X meses</option><option value="years">a cada X anos</option></select></label><label>intervalo<input type="number" min="1" value={f.interval} onChange={e=>u('interval',e.target.value)}/></label></div><label>horário<input type="time" value={f.time} onChange={e=>u('time',e.target.value)}/></label><label>termina em (opcional)<input type="date" value={f.endDate} onChange={e=>u('endDate',e.target.value)}/></label></div>}<button className="primary full" disabled={busy} onClick={()=>onSave(f)}>{busy?'salvando...':'salvar tarefa'}</button></Modal>}
function HabitModal({habit,onClose,onSave,busy}:{habit:Habit|null;onClose:()=>void;onSave:(f:any)=>void;busy:boolean}){const [f,setF]=useState<any>({name:habit?.name||'',description:habit?.description||'',icon:habit?.icon||'other',trackingType:habit?.tracking_type||'boolean',target:habit?.target||1,unit:habit?.unit||'vez',frequency:habit?.frequency||'daily',time:habit?.time||'',color:habit?.color||'pink'});const u=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));return <Modal title={habit?'editar hábito':'novo hábito'} onClose={onClose}><label>nome<input value={f.name} onChange={e=>u('name',e.target.value)} placeholder="ex.: beber água"/></label><label>descrição<input value={f.description} onChange={e=>u('description',e.target.value)} placeholder="opcional"/></label><div className="form-grid"><label>como acompanhar<select value={f.trackingType} onChange={e=>u('trackingType',e.target.value)}><option value="boolean">feito / não feito</option><option value="quantity">quantidade</option><option value="duration">tempo</option><option value="count">contagem</option></select></label><label>meta<input type="number" min="1" value={f.target} onChange={e=>u('target',e.target.value)}/></label></div>{f.trackingType!=='boolean'&&<label>unidade<input value={f.unit} onChange={e=>u('unit',e.target.value)} placeholder="ml, páginas, minutos..."/></label>}<div className="form-grid"><label>frequência<select value={f.frequency} onChange={e=>u('frequency',e.target.value)}><option value="daily">todos os dias</option><option value="weekdays">dias úteis</option><option value="weekly">semanal</option></select></label><label>horário opcional<input type="time" value={f.time} onChange={e=>u('time',e.target.value)}/></label></div><label>ícone<select value={f.icon} onChange={e=>u('icon',e.target.value)}>{Object.keys(icons).map(x=><option key={x}>{x}</option>)}</select></label><label>cor<select value={f.color} onChange={e=>u('color',e.target.value)}>{['pink','lavender','blue','sage','peach','yellow'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary full" disabled={busy} onClick={()=>onSave(f)}>{busy?'salvando...':'salvar hábito'}</button></Modal>}
function ProjectModal({onClose,onSave,busy}:{onClose:()=>void;onSave:(n:string,c:string)=>void;busy:boolean}){const [n,setN]=useState(''),[c,setC]=useState('pink');return <Modal title="novo projeto" onClose={onClose}><label>nome<input value={n} onChange={e=>setN(e.target.value)} placeholder="ex.: TCC"/></label><label>cor<select value={c} onChange={e=>setC(e.target.value)}>{['pink','lavender','blue','sage','yellow'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary full" disabled={busy} onClick={()=>onSave(n,c)}>{busy?'salvando...':'criar projeto'}</button></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:any}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button soft" onClick={onClose}><X/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')!).render(<App/>)
